### ISSUE TITLE
parseTranslationUnit and parseTranslationUnit2 wrong signatures?

### ISSUE THREAD

**Issue by david-bakin** [mjsabby/ClangSharp#2]
According to clang docs [here] (http://clang.llvm.org/doxygen/group__CINDEX__TRANSLATION__UNIT.html#ga494de0e725c5ae40cbdea5fa6081027d) the 5th parameter of `parseTranslationUnit2`, `struct CXUnsavedFile*`, is an *in* parameter (an array of struct) but ClangSharp has it as an *out* parameter.

And same for `parseTranslationUnit`.

**Comment by mjsabby** [comment]
The usage of the out parameter is to help marshal correctly. I could have also specified "ref" (which is really how the parameter is passed), but I chose not to because:

            int x;
            Foo(out x); // ok.

            int x;
            Foo(ref x); // compile error

Finally, the code is auto-generated, so special casing this instance would not be that great. The heuristic ClangSharp uses to make it an array of X versus making it an out X is if there is a const qualifier, which is present for the source_filename and command_line_args formal arguments to parseTranslationUnit but is missing for the unsaves_files parameter.

To unblock, I would do the following:

var x = new CXUnsavedFile[..];
parseTranslationUnit2(...., out x);

Furthermore, one of us should ask the Clang folks or submit a patch to make that parameter a const if it is indeed an "in" (which it looks like).

**Comment by david-bakin** [comment]
Ok.  I didn't know the marshalling would copy arguments both ways (in and
out) in the case of an out parameter.  Thanks!
