### ISSUE TITLE
How did you get libclang.dll and libLLVM.dll

### ISSUE THREAD

**Issue by david-bakin** [mjsabby/ClangSharp#3]
(I'm not sure an issue is the right way to deal with this but I didn't see any contact or discussion forum here or at www.clangsharp.org.)

I see at LLVMSharp that you have a nice script to generate libclang.dll and libLLVM.dll by first putting related libs into a library, running dumpbin to get the defined symbols, filtering for only the symbols you're interested in, placing them into a DEF file, and then linking the library to produce a dll.

Before I go down that path, can you tell me: If I chose to filter differently could I expose from a libclang.dll and/or libllvm.dll, that I create from a built clang/llvm, other valid entry points, such as the C++ interface to libTooling, or libASTMatchers?

Thanks!  -- David

(P.S., I do have your email address due to your answer to a previous issue but I wasn't sure I was invited to use it for questions.)

**Comment by mjsabby** [comment]
Creating an issue is fine.

The powershell script you are referring to is only there to generate libLLVM.dll because unlike libClang.dll (which is btw created by Clang's build scripts) libLLVM.dll is not supported by current LLVM build scripts on Windows; they are able to create libLLVM.so on Linux just fine -- so that script is really a workaround for a limitation in LLVM's build scripts.

libTooling and the ASTMatchers are C++ code, and are therefore significantly harder to interface with. For starters you would need the mangled names (https://github.com/mjsabby/ClangSharp/blob/master/Generated.cs#L1703) for the constructor, methods and destructor, hold on to the this pointer, and when you're calling an instance method, pass that in ... and all of that is the easy part :-)

There are more C++ ABI subtleties and compiler vendor nuances that will affect your ability to effectively work with it from C#.

If you don't need semantic analysis from Clang, and only need syntactic level detail, you can visit all Clang AST Nodes from ClangSharp, you just have to write a bit more code, but I feel very productive in C# and would have probably spent more time writing C++ despite using ASTMatchers, but that is me.

However, I understand where you're coming from: the ability to use ASTMatchers from C# would really make C++ code analysis a joy.

To that end I'm working to mirror the AST in ClangSharp and build an ASTMatcher-like framework, but it's a few months out. For semantic analysis, I'm going to use C++/CLI and expose the Clang sema class, and while I'm at it I'll probably also expose all the ASTMatchers, but it'll be Windows only solution where you must compile Clang with MSVC.

**Comment by david-bakin** [comment]
Thanks! I had not discovered for myself that clang builds libclang.dll (doh!).  I have just been investigating that and discovered how it exports symbols via Platform.h and Index.h.

I also discovered to my surprise that VC++ honors __declspec(dllexport) on incomplete class declarations (i.e., forward declarations)!  So that means that to export (C++ mangled) symbols for classes you simply create a header containing forward declarations of all the classes you'd like to export, each decorated with __declspec(dllexport), and then arrange for that file to be included in a certain few strategic header files (I haven't discovered those yet) so that it will be always read before any of its C++ classes are properly declared.

And after that I think using C++/CLI for shim or proxy classes is the way to go, as you suggest.  (Hopefully with a generator that creates them from the header files.)
